/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HBBC;

import UI.UI_Login;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        // TODO add your handling code here:
        UI_Login LoginForm = new UI_Login();
    
        // Make the UI_Registro form visible
        LoginForm.setVisible(true);

    }
}
